version: 1.0.0.1.{build}
configuration: Release
platform:
- Win32
- x64
build:
  project: luadbg_v15.sln
  verbosity: minimal
after_build:
- cmd: >-
    mkdir bin\x86

    mkdir bin\x64

    copy Release\luadbg_v15.dll bin\x86\luadbg.dll

    copy x64\Release\luadbg_v15.dll bin\x64\luadbg.dll

    7z a -tzip luadbg.zip bin\*
artifacts:
- path: luadbg.zip
  name: luadbg.zip
deploy:
- provider: GitHub
  auth_token:
    secure: xK4ZMxqQqd+NwhVJcXWTSQAryb1l8EQ7f0acKbyEVCygO/VEP9byuCj7v/YLSClf
  artifact: luadbg.zip
  draft: true