version: 1.0.2.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
configuration: Release
build_script:
- MSBuild.exe "luadbg_v15.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform="Win32"
- MSBuild.exe "luadbg_v15.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform="x64"
- mkdir bin\x86
- mkdir bin\x64
- copy Release\luadbg_v15.dll bin\x86\luadbg.dll
- copy x64\Release\luadbg_v15.dll bin\x64\luadbg.dll
- 7z a -tzip luadbg.zip bin\*
artifacts:
- path: luadbg.zip
  name: luadbg.zip
deploy:
- provider: GitHub
  auth_token:
    secure: xK4ZMxqQqd+NwhVJcXWTSQAryb1l8EQ7f0acKbyEVCygO/VEP9byuCj7v/YLSClf
  artifact: luadbg.zip
  draft: true